apiVersion: "v1"
kind: Service
metadata:
  name: hpa-example
  labels:
    name: hpa-example
    env: test
spec:
  type: NodePort
  ports:
    - nodePort: 32007
      port: 80
      name: hpa-example
  selector:
    name: hpa-example


#type: ClusterIP
#  ports:
#    - targetPort: 80
#      port: 80
#      name: web
#  selector:
#    name: web
